### ISSUE TITLE
Error retrieving derivatives

### ISSUE THREAD

**Issue by Psychedelic-Engineering** [Bynder/bynder-python-sdk#5]
When using the SDK to retrieve the derivatives of an account, 
`
from bynder_sdk import BynderClient
import configparser

config = configparser.ConfigParser()
config.read('bynder.ini')

bynder_client = BynderClient(
        base_url=config.get('BYNDER_TOKENS', 'base_url'),
        consumer_key=config.get('BYNDER_TOKENS', 'consumer_key'),
        consumer_secret=config.get('BYNDER_TOKENS', 'consumer_secret'),
        token=config.get('BYNDER_TOKENS', 'token'),
        token_secret=config.get('BYNDER_TOKENS', 'token_secret')
    )

print(bynder_client.derivatives())
`

it throws an exception:
`Traceback (most recent call last):
  File "/Users/makra/Library/Mobile Documents/com~apple~CloudDocs/S&V/UnitD/Eurobike/Byndertest/main.py", line 19, in <module>
    print(bynder_client.derivatives())
  File "/Users/makra/Byndertest/lib/python3.6/site-packages/bynder_sdk/client/bynder_client.py", line 116, in derivatives
    endpoint='/api/v4/derivatives/'
  File "/Users/makra/Byndertest/lib/python3.6/site-packages/bynder_sdk/oauth/oauth_request_handler.py", line 62, in get
    params=params
  File "/Users/makra/Byndertest/lib/python3.6/site-packages/bynder_sdk/oauth/oauth_request_handler.py", line 50, in _generic_request
    response.raise_for_status()
  File "/Users/makra/Byndertest/lib/python3.6/site-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://your-bynder-domain/api/v4/derivatives/`

If i open the API endpoint like it is specified in the documentation:
https://your-bynder-domain/api/v4/account/derivatives/
everything works and show the correct information. Please note the differences in the path between API and SDK.
In bynder_client.px line 116 the line should be changed to:
`
            endpoint='/api/v4/account/derivatives/'
`

**Comment by danielsequeira** [comment]
Hi @Psychedelic-Engineering,

Sorry for taking so long to get back to you. The problem here is that you are using the example `https://your-bynder-domain` as the domain for your Bynder account. You should replace it by your actual domain.

**Comment by danielsequeira** [comment]
Solved with https://github.com/Bynder/bynder-python-sdk/pull/8
